# Generated by Django 2.2 on 2019-04-23 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SpeciesObs',
            fields=[
                ('occurrence_id', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=10)),
                ('last_update_date', models.CharField(max_length=10)),
                ('last_status_change_date', models.CharField(max_length=10)),
                ('data_type', models.CharField(max_length=31)),
                ('scientific_name', models.CharField(db_index=True, max_length=255)),
                ('scientific_authority', models.CharField(max_length=255)),
                ('latitude_dd', models.CharField(max_length=31)),
                ('longitude_dd', models.CharField(max_length=31)),
                ('sampling_date', models.CharField(max_length=10)),
                ('sampling_year', models.CharField(db_index=True, max_length=4)),
                ('sampling_month', models.CharField(max_length=2)),
                ('sampling_day', models.CharField(max_length=2)),
                ('sample_min_depth', models.CharField(max_length=31)),
                ('sample_max_depth', models.CharField(max_length=31)),
                ('sampler_type', models.CharField(max_length=255)),
                ('dyntaxa_id', models.CharField(max_length=31)),
                ('taxon_kingdom', models.CharField(db_index=True, max_length=127)),
                ('taxon_phylum', models.CharField(db_index=True, max_length=127)),
                ('taxon_class', models.CharField(db_index=True, max_length=127)),
                ('taxon_order', models.CharField(db_index=True, max_length=127)),
                ('taxon_family', models.CharField(db_index=True, max_length=127)),
                ('taxon_genus', models.CharField(db_index=True, max_length=127)),
                ('taxon_species', models.CharField(db_index=True, max_length=127)),
                ('orderer', models.CharField(max_length=1023)),
                ('reporting_institute', models.CharField(max_length=1023)),
                ('sampling_laboratory', models.CharField(max_length=1023)),
                ('analytical_laboratory', models.CharField(max_length=1023)),
                ('dataset_name', models.CharField(db_index=True, max_length=255)),
                ('dataset_file_name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['occurrence_id'],
            },
        ),
    ]
