# Generated by Django 2.2 on 2019-04-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommandLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command_name', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=63)),
                ('started_datetime', models.DateTimeField(auto_now_add=True)),
                ('finished_datetime', models.DateTimeField(auto_now=True)),
                ('executed_by', models.CharField(max_length=255)),
                ('result_log', models.TextField()),
                ('debug_log', models.TextField()),
            ],
        ),
    ]
